# ─────────────────────────────────────────────────────────────────────────────
# docker‑compose.yml  (no hace falta el campo version)
# ─────────────────────────────────────────────────────────────────────────────

services:
  dat_service:
    image: lalvarezl/oracle-23ai-free:laal
    # indica que NUNCA intente bajar (pull) la imagen
    pull_policy: never
    container_name: mi-oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    environment:
      ORACLE_PWD: 1234

volumes:
  oracle_data:
    name: oracle_data
